CREATE DATABASE RESTAURANTSDB;
USE RESTAURANTSDB;

-- CRAEATING A CONSUMERS TABLES
 CREATE TABLE CONSUMERS (
 CONSUMER_ID VARCHAR(10) PRIMARY KEY,
 CITY VARCHAR(255),
 STATE VARCHAR(255),
 COUNTRY VARCHAR(255),
 LATITUDE DECIMAL(10,7),
 LONGITUDE DECIMAL(10,7),
 SMOKER VARCHAR(10),
 DRINK_LEVEL VARCHAR(50),
 TRANSPORTATION_METHOD VARCHAR(50),
 MARITAL_STATUS VARCHAR(20),
 CHILDREN VARCHAR(20),
 AGE INT,
 OCCUPATION VARCHAR(50),
 BUDGET VARCHAR(10)
 );
 
 -- CREATING A CONSUMER_PREFERENCES
  CREATE TABLE CONSUMER_PREFERENCES(
  CONSUMER_ID VARCHAR(10),
  PREFERRED_CUISINE VARCHAR(255),
  PRIMARY KEY (CONSUMER_ID, PREFERRED_CUISINE),
  foreign key (CONSUMER_ID) REFERENCES CONSUMERS(CONSUMER_ID) ON DELETE CASCADE
  );
  
  -- CREATING A RESTAURANTS TABLE
  CREATE TABLE RESTAURANTS (
  RESTAURANT_ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  CITY VARCHAR(255),
  STATE VARCHAR(255),
  COUNTRY VARCHAR(255),
  ZIP_CODE VARCHAR(255),
  LATITUDE DECIMAL(10,8),
  LONGITUDE DECIMAL(11,8),
  ALCOHOL_SERVICE VARCHAR(50),
  SMOKING_ALLOWED VARCHAR(50),
  PRICE VARCHAR(10),
  FRANCHISE VARCHAR(5),
  AREA VARCHAR(10),
  PARKING VARCHAR(50)
  );
  
  -- CREATING A RESTAURANT_CUISINES TABLE
  
  CREATE TABLE RESTAURANT_CUISINES (
  RESTAURANT_ID INT,
  CUISINE VARCHAR(255),
  PRIMARY KEY(RESTAURANT_ID, CUISINE),
  FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE
  );
  
  -- CREATING A RATING TABLE
  CREATE TABLE RATINGS (
  CONSUMER_ID VARCHAR(10),
  RESTAURANT_ID INT,
  OVERALL_RATING INT,
  FOOD_RATING INT,
  SERVICE_RATING INT,
  PRIMARY KEY (CONSUMER_ID, RESTAURANT_ID),
  FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMERS(CONSUMER_ID) ON DELETE CASCADE,
  FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE 
  );
  
  SELECT * FROM CONSUMERS;
  SELECT * FROM CONSUMER_PREFERENCES;
  SELECT * FROM RESTAURANTS;
  SELECT * FROM RESTAURANT_CUISINES;
  SELECT * FROM RATINGS;
  